### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-ui#108]
The default page when opening the dashboard is empty (currently showing "Page content"). We need to found what to show on the dashboard. It can be:

- no dashboard: the user is redirected on the page of the 1st service
- a dashboard: idk what we can put on it, maybe 2 buttons "services" and "deploy"

Any ideas?

**Comment by PaulFarault** [comment]
Having a dashboard seems to be important. It ca, contain:

- shortcuts to the past deployment page and to the new deployment page.
- list of useful links (as suggested by @mehdibn ).
- a card for each deployed service, which could display a status when available on the server.

**Comment by pvalentin01** [comment]
list of useful links (as suggested by @mehdibn ).

**Comment by pvalentin01** [comment]
@mehdibn  @rpignolet
could you specify the list of useful links as you suggested ?

**Comment by rpignolet** [comment]
The main problem is, `tdp-server` does not manage host directly, it does not know where UI are, it just launch playbooks which deploy TDP components and playbooks run on groups.
Moreover TDP components may not be directly accessible, behind a reverse proxy for example. So `tdp-server` need to know the public URL for theses components.

I think these 2 problems can't be resolved quickly, they need features not planned currently.
