### ISSUE TITLE
Legal mention in footer

### ISSUE THREAD

**Issue by PaulFarault** [TOSIT-IO/tdp-ui#134]
TDP-UI footers should contain license and copyright information.

**Comment by jpsavy** [comment]
What text for license and copyright information would you like to see in the footers,

**Comment by PaulFarault** [comment]
> Copyright 2022 [TOSIT](https://tosit.io/) | License [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0).

That seems enough, do you validate @rpignolet?

**Comment by rpignolet** [comment]
Yes good for me but replace 2022 with 2023.

**Comment by PaulFarault** [comment]
Time flies 😨
