### ISSUE TITLE
Run next dev outside of `tdp-ui` directory

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-ui#166]
I try to run `tdp-ui` outside of the project directory and it can not read the config file.

```
$ node --version
v16.19.0
$ npm --version
8.19.3
```

To reproduce:
```
git clone https://github.com/TOSIT-IO/tdp-ui.git
npm install ./tdp-ui
cp tdp-ui/config.example.json config.json
./node_modules/.bin/next dev tdp-ui
```
Output
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
warn  - The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
error - ../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
TypeError: Cannot read properties of undefined (reading 'config')
Import trace for requested module:
../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./src/styles/globals.css
./src/styles/globals.css
```

**Comment by PaulFarault** [comment]
Could you try this:

```bash
git clone https://github.com/TOSIT-IO/tdp-ui.git
npm install ./tdp-ui
cp tdp-ui/config.example.json tdp-ui/config.json
npm --prefix ./tdp-ui run dev
```

**Comment by rpignolet** [comment]
This is working if the `config.json` is inside `tdp-ui` directory. The `config.json` should be outside of `tdp-ui` directory.

**Comment by PaulFarault** [comment]
In exported mode, the config file is fetched from an URL. So you can save the `config.json` anywhere you want if you configure your NGINX accordingly.

In dev mode, config is read from the root of the repository. We can try to pass it as an argument if you think it's necessary?

**Comment by rpignolet** [comment]
It is not only for dev mode, in prod mode with Node we need to have an argument for the path of the config file.

**Comment by PaulFarault** [comment]
Do you want a prod mode using Node.js? Thought that one of the requirements was to use it only in exported mode?

**Comment by rpignolet** [comment]
From what I understood from Next, it can be used in production with Node or via export. I think both modes should be supported in production.

**Comment by PaulFarault** [comment]
Are you sure that it is relevant to maintain both of these deployment modes? It seems to over complicate the project at this point.

**Comment by rpignolet** [comment]
As discuss, the focus is for `next export` feature. The command `npm --prefix ./tdp-ui run dev` will do the job.
