### ISSUE TITLE
Problem with hard-coded shebang in generator.sh

### ISSUE THREAD

**Issue by gonzaloetjo** [TOSIT-IO/tdp-ui#171]
I propose to change from hard-coded to dynamic shebang in the generator.sh script. This is the same that is used in [setup.sh of getting-started](https://github.com/TOSIT-IO/tdp-getting-started/blob/master/scripts/setup.sh), which is useful for portability (nixos here).

**Comment by PaulFarault** [comment]
Sure, would be a good idea to use the same conventions as in other parts of the project!
