### ISSUE TITLE
Adapt generator.sh script to support air-gapped environment

### ISSUE THREAD

**Issue by sergkudinov** [TOSIT-IO/tdp-ui#194]
In air-gapped environment, we manage the `openapi-generator-cli-6.2.0.jar` file differently. So there is no need for `wget` to download it.

My suggestion is to add `--skip-download` option to `generate.sh` script and an `if` construction. I would also refactor `FORCE_OPENAPI_GEN` into cli command option `-f`/`--force` to make it look more fancy (similar to [`setup.sh`](https://github.com/TOSIT-IO/tdp-getting-started/blob/master/scripts/setup.sh))

**Comment by sergkudinov** [comment]
@rpignolet @PaulFarault

**Comment by rpignolet** [comment]
If the file `openapi-generator-cli-6.2.0.jar` is already present, the `generate.sh` script output this:
```
Downloading https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.2.0/openapi-generator-cli-6.2.0.jar
File ‘openapi-generator-cli.jar’ already there; not retrieving.
schemas/tdp-server_0.1.0_openapi.json: OK
No schema change. Skipping client generation...
If you want to force client generation, set the variable 'FORCE_OPENAPI_GEN=TRUE'
```
I think it already works, if the file is present the script will not download it no ?
